/* SPDX-License-Identifier: GPL-2.0-or-later */

#pragma once

#define VIAL_KEYBOARD_UID {0xBB, 0xD4, 0x5A, 0xD3, 0xBA, 0xB3, 0x67, 0x09}
#define ENCODER_RESOLUTION 2
#define RGB_MATRIX_FRAMEBUFFER_EFFECTS
#define RGB_MATRIX_KEYPRESSES
#define BACKLIGHT_BREATHING